name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '8.0' ]

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.operating-system}}

    steps:
      - uses: actions/checkout@v2
      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Show dir
        run: pwd
      - name: PHP Version
        run: php --version

      # Code quality

      - name: Execute tests (Unit and Feature tests) via PestPHP
        # Set environment
        env:
          SESSION_DRIVER: array
        run: vendor/bin/pest --coverage-clover clover.xml

      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        
